create extension if not exists pgcrypto;
create type public.app_role as enum ('user','admin');
create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,email text,preferred_name text,encouragement_style text,affirmation_style text,motivation_style text,business_motivation_preference text,daily_glam boolean default true,faith_based boolean default false,affirmations boolean default true,general_encouragement boolean default true,business_motivation boolean default true,onboarding_complete boolean default false,created_at timestamptz default now(),updated_at timestamptz default now());
create table public.user_roles(user_id uuid references auth.users(id) on delete cascade,role public.app_role not null default 'user',primary key(user_id,role));
create table public.plans(id uuid primary key default gen_random_uuid(),code text unique not null,name text not null,monthly_ai_allowance bigint default 0,is_active boolean default true,created_at timestamptz default now());
create table public.user_plan_status(user_id uuid primary key references auth.users(id) on delete cascade,plan_id uuid references public.plans(id),status text default 'free',period_start timestamptz,period_end timestamptz,created_at timestamptz default now());
create table public.user_preferences(user_id uuid primary key references auth.users(id) on delete cascade,generator_types jsonb default '[]',creative_outputs jsonb default '[]',favorite_styles jsonb default '[]',settings jsonb default '{}',created_at timestamptz default now(),updated_at timestamptz default now());
create table public.generator_projects(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,name text not null,description text,config jsonb default '{}',created_at timestamptz default now(),updated_at timestamptz default now());
create table public.saved_prompts(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,title text not null,content text not null,tags text[] default '{}',favorite boolean default false,created_at timestamptz default now(),updated_at timestamptz default now());
create table public.generator_vault_items(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,title text not null,item_type text not null,data jsonb default '{}',created_at timestamptz default now(),updated_at timestamptz default now());
create table public.idea_conversations(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,title text,created_at timestamptz default now(),updated_at timestamptz default now());
create table public.idea_messages(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,conversation_id uuid references public.idea_conversations(id) on delete cascade,role text not null,content text not null,created_at timestamptz default now());
create table public.saved_content(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,content_type text not null,title text,data jsonb default '{}',created_at timestamptz default now(),updated_at timestamptz default now());
create table public.daily_glam_history(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,content_type text not null,content text not null,created_at timestamptz default now());
create table public.uploaded_references(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,file_name text,storage_path text,mime_type text,created_at timestamptz default now());
create table public.ai_usage_events(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,request_type text not null,provider text,model text,input_tokens bigint,output_tokens bigint,estimated_credits numeric,tts_chars bigint,success boolean default true,error_category text,created_at timestamptz default now());

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,email) values(new.id,new.email); insert into public.user_roles(user_id,role) values(new.id,'user'); insert into public.user_preferences(user_id) values(new.id); return new; end $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security; alter table public.user_roles enable row level security; alter table public.user_plan_status enable row level security; alter table public.user_preferences enable row level security; alter table public.generator_projects enable row level security; alter table public.saved_prompts enable row level security; alter table public.generator_vault_items enable row level security; alter table public.idea_conversations enable row level security; alter table public.idea_messages enable row level security; alter table public.saved_content enable row level security; alter table public.daily_glam_history enable row level security; alter table public.uploaded_references enable row level security; alter table public.ai_usage_events enable row level security;

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.user_roles where user_id=auth.uid() and role='admin') $$;

create policy "profiles own select" on public.profiles for select using(id=auth.uid()); create policy "profiles own update" on public.profiles for update using(id=auth.uid()) with check(id=auth.uid());
create policy "roles own select" on public.user_roles for select using(user_id=auth.uid() or public.is_admin());
create policy "plan own select" on public.user_plan_status for select using(user_id=auth.uid() or public.is_admin());
create policy "prefs own all" on public.user_preferences for all using(user_id=auth.uid()) with check(user_id=auth.uid());

DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['generator_projects','saved_prompts','generator_vault_items','idea_conversations','idea_messages','saved_content','daily_glam_history','uploaded_references','ai_usage_events'] LOOP EXECUTE format('create policy %I on public.%I for select using(user_id=auth.uid())',t||'_sel',t); EXECUTE format('create policy %I on public.%I for insert with check(user_id=auth.uid())',t||'_ins',t); EXECUTE format('create policy %I on public.%I for update using(user_id=auth.uid()) with check(user_id=auth.uid())',t||'_upd',t); EXECUTE format('create policy %I on public.%I for delete using(user_id=auth.uid())',t||'_del',t); END LOOP; END $$;

create index on public.generator_projects(user_id,created_at desc); create index on public.saved_prompts(user_id,created_at desc); create index on public.ai_usage_events(user_id,created_at desc); create index on public.saved_content(user_id,content_type,created_at desc);
insert into public.plans(code,name,monthly_ai_allowance) values('free','Free',0) on conflict(code) do nothing;
